// Raffle Configuration
// Edit this file to update ticket numbers per contest.
// Each contest has its own independent ticket pool (numbers can repeat
// across contests) and exactly one winner.

export const contests = [
  {
    slug: "fio-de-prata",
    name: "Fio de Prata",
    logo: "assets/logo_fio_prata.png",
    soldTickets: {
      1: "Noémia",
      2: "Pedro Fernandes",
      3: "Dulce Curto",
      4: "Isabel",
      5: "Manuela Arneiro",
      6: "Paulo Azeiteiro",
      7: "Noémia",
      8: "Fernanda Troca",
      9: "Pedro Fernandes",
      10: "Elsa",
      11: "João Pires",
      12: "David",
      13: "Noémia",
      14: "Manuela Arneiro",
      15: "Manuela Arneiro",
      16: "Maria do Céu",
      17: "Noémia",
      18: "Maria Lopes",
      19: "Maria Lopes",
      20: "Noémia",
      21: "Mário Caramujo",
      22: "Fernanda Tabanez",
      23: "Ana Afonso",
      24: "Manuela Arneiro",
      25: "Manuela Zagalo",
      27: "Manuela Arneiro",
      28: "Manuela Arneiro",
      29: "Helena Rocha",
      31: "Tio Júlio",
      33: "Carlos Gomes",
      36: "Ilda Neves",
      37: "Santiago Barreto",
      39: "Carmelinda",
      42: "Tio Júlio",
      43: "Tio João",
    },
  },
  {
    slug: "clifebres",
    name: "Clifebres",
    logo: "assets/logo_clifebres.png",
    soldTickets: {
      1: "Dulce Curto",
      2: "João Alcides",
      3: "Sandra Regateiro",
      6: "Fernando Troca",
      9: "Fernando Troca",
      10: "João Alcides",
      11: "Sandra Regateiro",
      14: "David",
      17: "Paulo Azeiteiro",
      18: "Silvério Silva",
      19: "Tibério Silva",
      21: "Elsa",
      26: "Helena Rocha",
      28: "Poeta",
      29: "Carlos Azeiteiro",
      35: "Carlos Gomes",
      41: "Santiago Barreto",
    },
  },
  {
    slug: "pascoas",
    name: "Páscoas",
    logo: "assets/logo_pascoas.png",
    soldTickets: {
      4: "Eliana Neves",
      5: "Fernando Troca",
      6: "Amadeu Ramos",
      10: "Cesaltina",
      11: "Elsa",
      12: "Eliana Neves",
      14: "Dulce Curto",
      15: "Cesaltina",
      17: "Paulo Azeiteiro",
      18: "Amadeu Ramos",
      21: "David",
      22: "Paulo Azeiteiro",
      23: "Carla Silva",
      25: "Helena Rocha",
      26: "Oriana Simões",
      28: "Carla Silva",
      29: "Carlos Azeiteiro",
      32: "Santiago Barreto",
      36: "Carlos Gomes",
    },
  },
];
